### ISSUE TITLE
error by loading geyser-fabric-2.3.2-SNAPSHOT+build.697.jar 

### ISSUE THREAD

**Issue by masterblaster221** [GeyserMC/Hydraulic#20]
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:421)
	at java.base/java.lang.Class.forName(Class.java:412)
	at org.geysermc.geyser.util.FileUtils.lambda$getGeneratedClassesForAnnotation$0(FileUtils.java:235)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.geysermc.geyser.util.FileUtils.getGeneratedClassesForAnnotation(FileUtils.java:240)
	at org.geysermc.geyser.util.FileUtils.getGeneratedClassesForAnnotation(FileUtils.java:217)
	at org.geysermc.geyser.registry.populator.PacketRegistryPopulator.populate(PacketRegistryPopulator.java:40)
	at org.geysermc.geyser.registry.Registries.<clinit>(Registries.java:190)
	at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:213)
	at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:793)
	at org.geysermc.geyser.platform.mod.GeyserModBootstrap.onGeyserEnable(GeyserModBootstrap.java:112)
	at org.geysermc.geyser.platform.fabric.GeyserFabricBootstrap.lambda$onInitialize$0(GeyserFabricBootstrap.java:53)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$zek000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2578)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:662)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Mixin transformation of org.geysermc.geyser.util.InventoryUtils failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.geysermc.geyser.translator.protocol.java.JavaUpdateRecipesTranslator.<clinit>(JavaUpdateRecipesTranslator.java:77)
	... 25 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 30 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method findOrCreateItemCreative(Lorg/geysermc/geyser/session/GeyserSession;Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lcom/llamalad7/mixinextras/sugar/ref/LocalBooleanRef;)V in hydraulic.mixins.json:ext.InventoryUtilsMixin from mod hydraulic failed injection check, (0/1) succeeded. Scanned 1 target(s). No refMap loaded.
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at com.llamalad7.mixinextras.wrapper.InjectorWrapperImpl.doPostInject(InjectorWrapperImpl.java:79)
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.doPostInject(SugarWrapperImpl.java:84)
	at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.postInject(WrapperInjectionInfo.java:78)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 33 more

**Comment by rtm516** [comment]
Hydraulic hasn't been updated for 1.21
